### PR TITLE
Add potential targets to link_package

### PR DESCRIPTION
**Pull request by fsimonis**
This PR adds a potential target name to the `link_library` arguments .

On systems where libraries ship with a CMake config file, the `find_package(X)` call will set `X_FOUND` and provide a target `X::X`, but will not set `X_LIBRARIES` nor `X_INCLUDE_DIRS`.  
This change now links to the given target if available and falls back to the CMake variables.

Furthermore, some find modules such as FindSDL only set the old `X_LIBRARY` and `X_INCLUDE_DIR` variables. This PR also adds the old variables to the link and include commands.

`cmake_parse_arguments` increases the required CMake version to `3.7.2`.

### CODE REVIEW

**Comment by DerDakon** [comment]
Which modules only provide *_DIR and *_LIBRARY? The ones provided by CMake should not, and the ones introduced in this branch should neither, otherwise they should simply be fixed.

**Comment by fsimonis** [comment]
@DerDakon [FindSDL](https://cmake.org/cmake/help/latest/module/FindSDL.html) shipped with CMake is an example, which is relevant for the project.

**Comment by DerDakon** [comment]
Oh my goodness. The [bug](https://gitlab.kitware.com/cmake/cmake/-/issues/12911) is only 8 years old.

**Comment by minexew** [comment]
@DerDakon I believe the current CMake policy is [to not bundle _Find*_ files for third-party libraries](https://cmake.org/Bug/view.php?id=14826#c35490) in the first place -- e.g. they don't provide one for SDL2 at all.

**Comment by DerDakon** [comment]
Sure, I know. But there is a FindSDL and that is ugly regarding the variables. Contributions welcome, otherwise it would stay as it is.

**Comment by minexew** [comment]
I get you. Will look into proposing an upstream patch.

**Comment by TrueBrain** [comment]
CMake just got merged upstream; would you mind re-targeting your PR there? (most likely it requires opening a new PR :D). Tnx!!

**Pull request closed without merging**
